### ISSUE TITLE
run Ship detection notebook. Error found

### ISSUE THREAD

**Issue by huayue21** [CS-SI/eodag#148] opened 2020-12-31 00:58 UTC
```
graph_process = os.path.join(workspace, 'ShipDetection.xml')
with open(graph_process, 'w') as g_2:
    g_2.write(
"""
<graph id="Graph">
  <version>1.0</version>
    <node id="Read">
      <operator>Read</operator>
      <sources/>
      <parameters>
        <file>${inputproduct}</file>
      </parameters>
    </node>
    <node id="Land-Sea-Mask">
      <operator>Land-Sea-Mask</operator>
      <sources>
        <sourceProduct refid="Read"/>
      </sources>
      <parameters>
        <geometry>Gulf_of_Trieste_seamask_UTM33</geometry>
        <landMask>false</landMask>
        <useSRTM>false</useSRTM>
        <shorelineExtension>10</shorelineExtension>
      </parameters>
    </node>
    <node id="Calibration">
```

GPT complain on this line
`  <geometry>Gulf_of_Trieste_seamask_UTM33</geometry>`:

expression: Undefined symbol 'Gulf_of_Trieste_seamask_UTM33'. due to Undefined symbol 'Gulf_of_Trieste_seamask_UTM33'.
 done.

I actually checked the file of the first step:
S1A_IW_GRDH_1SDV_20161009T165807_4550_Orb.dim
And did found there is vector data with the same name.

**Comment by sbrunato** [comment] 2021-01-05 10:14
Hello, what version of eodag are you running ?
You should use v1.6.0 or newer, as the notebook got some fixes lately https://github.com/CS-SI/eodag/commits/master/examples/tuto_ship_detection.ipynb

**Comment by maximlt** [comment] 2021-02-19 15:32
Hi @huayue21,
We've recently updated the ship detection notebook and it works fine. It contains now some more information about how to setup SNAP and the additional dependencies required to run the notebook correctly. Hope it helps you!

**Comment by maximlt** [comment] 2021-03-24 15:28
Closing since the notebook worked fine when I updated it. I'll reopen it if @huayue21 indicates that the problem is still there.

**Closed by maximlt** 2021-03-24 15:28 UTC
Labels: question

**Comment by estambolieva** [comment] 2021-04-10 11:28
Hi @maximlt 

I have the same problem while using SNAP 6.0:

```
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
Executing processing graph
INFO: org.hsqldb.persist.Logger: dataFileCache open start
expression: Undefined symbol 'Gulf_of_Trieste_seamask_UTM33'. due to Undefined symbol 'Gulf_of_Trieste_seamask_UTM33'.
 done.

Error: [NodeId: Land-Sea-Mask] expression: Undefined symbol 'Gulf_of_Trieste_seamask_UTM33'. due to Undefined symbol 'Gulf_of_Trieste_seamask_UTM33'.
```

It seems that `Gulf_of_Trieste_seamask_UTM33` is in the `orb` file:

```
<MDElem name="parameters">
                        <MDATTR name="separateShapes" type="ascii">false</MDATTR>
                        <MDATTR name="vectorFile" type="ascii">eodag_workspace_shipdetection/auxdata/Gulf_of_Trieste_seamask_UTM33.shp</MDATTR>
                    </MDElem>
```

**Comment by maximlt** [comment] 2021-04-10 15:49
Hi @estambolieva,

Thanks for this report! I note that you are using SNAP 6.0 while the tutorial indicates that the version used to run it was SNAP 8.0. Could you try with this version instead?

Out of curiosity, would you mind replying to these questions?

* In the first place, were you looking for a tool such as EODAG (i.e. search/download EO products) or were you more interested in this specific tutorial about ship detection or were you just looking for a tutorial with SNAP?
* Have you also run the two other tutorials that makes use of SNAP (detect burnt areas)?

I'm asking because we're reworking the documentation currently and we're not sure to keep these 3 tutorials:

* They don't say much about EODAG itself, it's more about processing images with SNAP/Sen2Cor/snappy
* They are difficult to maintain

**Comment by estambolieva** [comment] 2021-04-10 21:30
Hi @maximlt,

  thanks a lot for the quick reply!

  I downgraded SNAP to version 6.0 from 8.0 as SNAP 8.0 had a connection timeout problem (also mentioned [here](https://forum.step.esa.int/t/orbit-file-timeout-march-2021/28621))

```
Connect to qc.sentinel1.eo.esa.int:443 [qc.sentinel1.eo.esa.int/131.176.235.71] failed: Connection timed out (Connection timed out) due to Connection timed out (Connection timed out)
``` 

  What is your suggestion for getting the code up and running?

Answers:

- manipulating sat. images
- I have not run the other tutorials yet, but I will gladly do so :) Oh, how long would they be online for?

Cheers, K.

**Comment by maximlt** [comment] 2021-04-11 10:00
Ush I had a look at the link you shared, you're not the only one experiencing this issue! I'm sorry I have no suggestion for how to fix this, your best luck is to find a solution or workaround in that discussion you shared.

Ok thanks a lot for replying to my questions :+1: 

We will have a discussion to see whether we should keep these tutorials around. If we remove them from the official documentation or the repo, they would anyway still be available from the previous version tags.
