### ISSUE TITLE
Download paths not consistent

### ISSUE THREAD

**Issue by ds2268** [CS-SI/eodag#548] opened 2022-11-08 19:02 UTC
**Describe the bug**
The download path differs for different providers and it's not consistent. This is the case for Creodias and Onda providers (at least).

**Code To Reproduce**
```
dag = EODataAccessGateway(eodag_cfg)
dag.set_preferred_provider("creodias") # or "onda"
# ...
# Search for a EOProduct
# ...
dl_path = rnd_product.download()
```

**Output**

`dl_path` for Creodias:

`...some_prefix../S2B_MSIL1C_20180805T102019_N0206_R065_T32TMT_20180805T142133.SAFE/**S2B_MSIL1C_20180805T102019_N0206_R065_T32TMT_20180805T142133.SAFE**`

`dl_path` for Onda:

`...some_prefix../S2B_MSIL1C_20180805T102019_N0206_R065_T32TMT_20180805T142133.SAFE`

Despite the actual folder being the **same**, the returned path is different! This breaks automated pipelines.
The problem is what Onda returns, as it returns the path of 1 level up, despite the actual folder structure is the same as Creodias.

**Environment:**
 - Python version: 3.9
 - EODAG version: 2.6.0

**Comment by sbrunato** [comment] 2022-11-09 09:00
Thanks for submitting this issue @ds2268 . It is related to https://github.com/CS-SI/eodag/issues/251, and this is an issue that should be fixed

**Comment by ds2268** [comment] 2022-11-09 12:04
Yes, I have also voted in #446 . Thank you!

**Comment by sbrunato** [comment] 2022-11-16 11:04
duplicate of #251

**Closed by sbrunato** 2022-11-16 11:04 UTC
Labels: bug
